### ISSUE TITLE
Add "atomic host softreboot" to softreboot using kexec instead a full reboot

### ISSUE THREAD

**Issue by e-minguez** [projectatomic/atomic#27]
Wouldn't be nice to use kexec to softreboot your atomic host instead a full reboot specially for baremetal atomic hosts?

**Comment by jeremyeder** [comment]
I do agree reboot times in bare metal are really a PITA. So, I also do this kexec trick all the time.

But, IMO this is not supportable because I've run into situations where the kexec'd kernel has problem with hardware (perhaps some state was not re-initialized as it would be on a normal boot), and you have to be very careful to quiesce userspace, page cache, apps, any in-flight data before kexec'ing (which is what the system does on shutdown anyway, and does it "right").

So, for debug and developers something like this:

```
function kx {
        for i in `grep menuentry /boot/grub2/grub.cfg | grep el | awk '{print $9}' | sed -e "s/'//g"`
        do
                export KERNEL=$i
                echo kexec -l /boot/vmlinuz-$KERNEL --initrd=/boot/initramfs-$KERNEL.img --reuse-cmdline
        done
        echo "kexec -e"
}
```

**Comment by rhatdan** [comment]
@cgwalters @e-minguez @jeremyeder  Looking at old issues on atomic, what should we do with this?

**Comment by e-minguez** [comment]
If it's going to be unreliable, then forget it. 
Cherrs

**Comment by jeremyeder** [comment]
@e-minguez still ok for dev ;) use the bash function in my previous comment.  But yeah, doesn't belong in any supported product.  Sadly booting bare metal takes forever, and it's not getting any faster...

**Comment by e-minguez** [comment]
Just to notice that Fedora 23 (https://docs.fedoraproject.org/en-US/Fedora/23/html/Release_Notes/sect-Release_Notes-Changes_for_Sysadmin.html) has a new "reboot --kexec" flag :)
```
The reboot command has a new option: --kexec. Use this option to reboot into the new system using the kexec kernel switching mechanism instead of a full reboot, bypassing the BIOS/Firmware and boot loader.
```
