### ISSUE TITLE
skopeo issue when running atomic install --system on f24

### ISSUE THREAD

**Issue by aveshagarwal** [projectatomic/atomic#399]
When installing flannel container image with atomic, it errors on skopeo when infact skopeo is already installed on the system:

```
#rpm -qa|grep skopeo
skopeo-0.1.12-2.fc24.x86_64

#atomic install --system flannel
skopeo must be installed to perform remote inspections
```

**Comment by aveshagarwal** [comment]
@giuseppe

**Comment by giuseppe** [comment]
@aveshagarwal now sure why, but it seems the version of skopeo is old.  If you try: "skopeo inspect docker://busybox" does it work for you?  It fails for me saying "Please use a fully qualified repository name", this was changed in some new version of Skopeo

@runcom

**Comment by runcom** [comment]
The atomic 1.10 is broken for various reasons in F24. I have to also rebuild skopeo tomorrow.

**Comment by aveshagarwal** [comment]
@giuseppe I will try and let you know but this is the default skopeo version I got as a dependency when installaing atomic on f24.

**Comment by aveshagarwal** [comment]
@giuseppe @runcom 

```
# skopeo inspect docker://busybox
/usr/bin/skopeo: line 1: syntax error near unexpected token `newline'
/usr/bin/skopeo: line 1: `!<arch>'

# skopeo inspect -h
/usr/bin/skopeo: line 1: syntax error near unexpected token `newline'
/usr/bin/skopeo: line 1: `!<arch>'
```

**Comment by runcom** [comment]
I'm aware of that, skopeo needs to be rebuilt in F23 and F24. I'm going to do this first thing tomorrow. After that we need to tag another atomic point release and rebuild atomic 1.10.x as well. There's also an outstanding question for @rhatdan about which version of docker-storage to use because atomic 1.10.x needs --reset flag in docker-storage. 

After of all that is done, I'll release another atomic update.

**Comment by rhatdan** [comment]
I believe this is fixed in the current release.  Reopen if it is still a problem.
