### ISSUE TITLE
support `readonly: false` system containers

### ISSUE THREAD

**Issue by pschiffe** [projectatomic/atomic#801]
When trying to install system container with rw rootfs I get:
```
$ sudo atomic install --system ga
Extracting to /var/lib/containers/atomic/ga.0
Invalid configuration file.  Only readonly images are supported
```

```
...
    "root": {
        "path": "rootfs",
        "readonly": false
    },
...
```

There is also a problem with oci-systemd-hook https://github.com/projectatomic/oci-systemd-hook/issues/37

**Comment by giuseppe** [comment]
this is not possible using ostree as a backend.  We would need to copy the files instead of using the ostree checkout with hard links for this (doable but when doing this we wanted to use read only images anyway as they can be mounted/shared from a network location).

If you force "readonly": false, as it is now, it will corrupt the ostree storage.

**Comment by pschiffe** [comment]
I see. Feel free to close the issue then.

**Comment by rhatdan** [comment]
Thanks @giuseppe I had not understood what was going on.  I guess in order to support this we would need overlay or something on the mount point.  But for the time being we should force all content to be precreated.  Or use a different form of storage then OSTree.  container/storage when it becomes available.
